INSERT INTO 
    course
VALUES
    -- Computer Science Courses
    ('cs101', 'Introduction to Programming', 'computer science', 4),
    ('cs102', 'Data Structures', 'computer science', 4),
    ('cs201', 'Algorithms', 'computer science', 3),
    ('cs202', 'Computer Organization', 'computer science', 3),
    ('cs301', 'Operating Systems', 'computer science', 3),
    ('cs302', 'Database Systems', 'computer science', 3),
    ('cs401', 'Artificial Intelligence', 'computer science', 4),
    ('cs402', 'Machine Learning', 'computer science', 4),
    -- Software Engineering Courses
    ('seng101', 'Introduction to Software Engineering', 'software engineering', 4),
    ('seng102', 'Software Requirements', 'software engineering', 4),
    ('seng201', 'Software Design', 'software engineering', 3),
    ('seng202', 'Software Testing', 'software engineering', 3),
    ('seng301', 'Agile Software Development', 'software engineering', 3),
    ('seng302', 'Software Project Management', 'software engineering', 3),
    ('seng401', 'Software Architecture', 'software engineering', 4),
    ('seng402', 'Advanced Software Engineering', 'software engineering', 4),
    -- Computer Engineering Courses
    ('comp101', 'Introduction to Computer Engineering', 'computer engineering', 4),
    ('comp102', 'Digital Logic Design', 'computer engineering', 4),
    ('comp201', 'Microprocessors', 'computer engineering', 3),
    ('comp202', 'Embedded Systems', 'computer engineering', 3),
    ('comp301', 'Computer Networks', 'computer engineering', 3),
    ('comp302', 'VLSI Design', 'computer engineering', 3),
    ('comp401', 'Computer Vision', 'computer engineering', 4),
    ('comp402', 'High Performance Computing', 'computer engineering', 4),
    -- Electrical Engineering Courses
    ('elec101', 'Circuit Analysis', 'electrical engineering', 4),
    ('elec102', 'Electromagnetics', 'electrical engineering', 4),
    ('elec201', 'Analog Electronics', 'electrical engineering', 3),
    ('elec202', 'Signals and Systems', 'electrical engineering', 3),
    ('elec301', 'Digital Signal Processing', 'electrical engineering', 3),
    ('elec302', 'Power Electronics', 'electrical engineering', 3),
    ('elec401', 'Control Systems', 'electrical engineering', 4),
    ('elec402', 'Electrical Machines', 'electrical engineering', 4),
    -- Mechanical Engineering Courses
    ('mech101', 'Engineering Mechanics', 'mechanical engineering', 4),
    ('mech102', 'Thermodynamics', 'mechanical engineering', 4),
    ('mech201', 'Fluid Mechanics', 'mechanical engineering', 3),
    ('mech202', 'Heat Transfer', 'mechanical engineering', 3),
    ('mech301', 'Mechanical Vibrations', 'mechanical engineering', 3),
    ('mech302', 'Dynamics of Machinery', 'mechanical engineering', 3),
    ('mech401', 'Robotics', 'mechanical engineering', 4),
    ('mech402', 'Advanced Thermodynamics', 'mechanical engineering', 4),
    -- Civil Engineering Courses
    ('civ101', 'Introduction to Civil Engineering', 'civil engineering', 4),
    ('civ102', 'Structural Analysis', 'civil engineering', 4),
    ('civ201', 'Geotechnical Engineering', 'civil engineering', 3),
    ('civ202', 'Construction Materials', 'civil engineering', 3),
    ('civ301', 'Hydraulics', 'civil engineering', 3),
    ('civ302', 'Transportation Engineering', 'civil engineering', 3),
    ('civ401', 'Structural Design', 'civil engineering', 4),
    ('civ402', 'Environmental Engineering', 'civil engineering', 4),
    -- Physics Courses
    ('phy101', 'Introduction to Physics', 'physics', 4),
    ('phy102', 'Mechanics', 'physics', 4),
    ('phy201', 'Electromagnetism', 'physics', 3),
    ('phy202', 'Quantum Mechanics', 'physics', 3),
    ('phy301', 'Thermal Physics', 'physics', 3),
    ('phy302', 'Solid State Physics', 'physics', 3),
    ('phy401', 'Nuclear Physics', 'physics', 4),
    ('phy402', 'Particle Physics', 'physics', 4),
    -- Chemistry Courses
    ('chem101', 'Introduction to Chemistry', 'chemistry', 4),
    ('chem102', 'Organic Chemistry', 'chemistry', 4),
    ('chem201', 'Inorganic Chemistry', 'chemistry', 3),
    ('chem202', 'Physical Chemistry', 'chemistry', 3),
    ('chem301', 'Analytical Chemistry', 'chemistry', 3),
    ('chem302', 'Biochemistry', 'chemistry', 3),
    ('chem401', 'Industrial Chemistry', 'chemistry', 4),
    ('chem402', 'Environmental Chemistry', 'chemistry', 4),
    -- Biology Courses
    ('bio101', 'Introduction to Biology', 'biology', 4),
    ('bio102', 'Cell Biology', 'biology', 4),
    ('bio201', 'Genetics', 'biology', 3),
    ('bio202', 'Microbiology', 'biology', 3),
    ('bio301', 'Ecology', 'biology', 3),
    ('bio302', 'Molecular Biology', 'biology', 3),
    ('bio401', 'Evolutionary Biology', 'biology', 4),
    ('bio402', 'Biotechnology', 'biology', 4);