INSERT INTO
    student (name, dept_name, tot_cred)
VALUES
    -- Computer Science
    ('ahmet can', 'computer science', 45),
    ('ayse yilmaz', 'computer science', 55),
    ('mehmet kaya', 'computer science', 30),
    ('fatma demir', 'computer science', 40),
    ('burak tan', 'computer science', 60),
    ('selin onat', 'computer science', 25),
    ('canan yilmaz', 'computer science', 50),
    ('enes kaya', 'computer science', 35),
    ('cem yilmaz', 'computer science', 42),
    ('gizem kara', 'computer science', 48),
    ('elif yilmaz', 'computer science', 52),
    ('veli kaya', 'computer science', 57),
    ('gokhan aydin', 'computer science', 36),
    ('selin tan', 'computer science', 47),
    ('nur karaca', 'computer science', 33),
    ('meltem demir', 'computer science', 29),
    ('hasan aydin', 'computer science', 45),
    ('kemal onur', 'computer science', 41),
    ('ziya gunes', 'computer science', 56),
    ('arda yilmaz', 'computer science', 34),
    ('furkan tan', 'computer science', 40),
    ('mert yildiz', 'computer science', 51),
    ('ayse gunes', 'computer science', 60),
    ('yusuf kara', 'computer science', 28),
    ('seda kaya', 'computer science', 49),
    -- Software Engineering
    ('emre uzun', 'software engineering', 39),
    ('berna yilmaz', 'software engineering', 57),
    ('koray tan', 'software engineering', 44),
    ('yigit kaya', 'software engineering', 32),
    ('ece yilmaz', 'software engineering', 53),
    ('irem kara', 'software engineering', 61),
    ('kadir demir', 'software engineering', 26),
    ('dilara tan', 'software engineering', 50),
    ('oguz yildiz', 'software engineering', 36),
    ('arda tan', 'software engineering', 40),
    ('tugce kaya', 'software engineering', 46),
    ('cansu yilmaz', 'software engineering', 55),
    ('mert tan', 'software engineering', 59),
    ('deniz kara', 'software engineering', 60),
    ('bora demir', 'software engineering', 48),
    ('gokce onat', 'software engineering', 33),
    ('zeynep kaya', 'software engineering', 38),
    ('ugur tan', 'software engineering', 31),
    ('serra tan', 'software engineering', 37),
    -- Computer Engineering
    ('furkan kaya', 'computer engineering', 54),
    ('kaan tan', 'computer engineering', 30),
    ('melis yilmaz', 'computer engineering', 51),
    ('emre kara', 'computer engineering', 29),
    ('gokhan tan', 'computer engineering', 50),
    ('aylin yilmaz', 'computer engineering', 58),
    ('nuri kaya', 'computer engineering', 40),
    ('ezgi yilmaz', 'computer engineering', 35),
    ('kemal tan', 'computer engineering', 43),
    ('serap tan', 'computer engineering', 60),
    ('sinan yilmaz', 'computer engineering', 56),
    ('elif demir', 'computer engineering', 27),
    ('okan tan', 'computer engineering', 53),
    ('sinem kaya', 'computer engineering', 39),
    ('umit yilmaz', 'computer engineering', 52),
    -- Electrical Engineering
    ('yigit gunes', 'electrical engineering', 47),
    ('elif kaya', 'electrical engineering', 42),
    ('emir tan', 'electrical engineering', 38),
    ('ozlem kara', 'electrical engineering', 55),
    ('sahin yilmaz', 'electrical engineering', 50),
    ('emel tan', 'electrical engineering', 62),
    ('omer kaya', 'electrical engineering', 30),
    ('gamze demir', 'electrical engineering', 58),
    ('beyza tan', 'electrical engineering', 45),
    ('mustafa yilmaz', 'electrical engineering', 41),
    ('tamer kaya', 'electrical engineering', 34),
    ('fatih tan', 'electrical engineering', 39),
    ('kenan yilmaz', 'electrical engineering', 51),
    ('burcu kara', 'electrical engineering', 36),
    ('eren tan', 'electrical engineering', 48),
    -- Mechanical Engineering
    ('erdem kaya', 'mechanical engineering', 60),
    ('hasan tan', 'mechanical engineering', 30),
    ('meltem yilmaz', 'mechanical engineering', 52),
    ('yasar kara', 'mechanical engineering', 29),
    ('mert tan', 'mechanical engineering', 47),
    ('didem yilmaz', 'mechanical engineering', 54),
    ('cihan kaya', 'mechanical engineering', 31),
    ('merve demir', 'mechanical engineering', 42),
    ('enes tan', 'mechanical engineering', 38),
    ('kerem yilmaz', 'mechanical engineering', 46),
    ('duygu kara', 'mechanical engineering', 59),
    ('sefa tan', 'mechanical engineering', 35),
    ('hande yilmaz', 'mechanical engineering', 56),
    ('berkay kaya', 'mechanical engineering', 33),
    ('taner tan', 'mechanical engineering', 40),
    -- Civil Engineering
    ('didem yilmaz', 'civil engineering', 43),
    ('kemal kaya', 'civil engineering', 30),
    ('aylin tan', 'civil engineering', 57),
    ('elif yilmaz', 'civil engineering', 34),
    ('serkan kara', 'civil engineering', 55),
    ('zeynep yilmaz', 'civil engineering', 60),
    ('volkan kaya', 'civil engineering', 45),
    ('sezgin tan', 'civil engineering', 49),
    ('gulsah yilmaz', 'civil engineering', 32),
    ('serdar tan', 'civil engineering', 52),
    ('buket kara', 'civil engineering', 46),
    ('onur tan', 'civil engineering', 40),
    ('fatih yilmaz', 'civil engineering', 48),
    ('funda kaya', 'civil engineering', 33),
    ('nurdan yilmaz', 'civil engineering', 36),
    -- Physics
    ('cagri tan', 'physics', 42),
    ('bahar yilmaz', 'physics', 39),
    ('ilker kaya', 'physics', 51),
    ('onur tan', 'physics', 34),
    ('burak yilmaz', 'physics', 30),
    ('selin kaya', 'physics', 47),
    ('ozan yilmaz', 'physics', 60),
    ('pelin tan', 'physics', 58),
    ('ozlem kaya', 'physics', 37),
    ('nazan yilmaz', 'physics', 44),
    -- Chemistry
    ('necla tan', 'chemistry', 55),
    ('gokce yilmaz', 'chemistry', 32),
    ('burak kaya', 'chemistry', 49),
    ('ipek yilmaz', 'chemistry', 39),
    ('berke tan', 'chemistry', 46),
    ('aleyna kaya', 'chemistry', 41),
    ('yagmur yilmaz', 'chemistry', 36),
    ('okan tan', 'chemistry', 50),
    ('tuce kaya', 'chemistry', 59),
    ('nazim yilmaz', 'chemistry', 53),
    -- Biology
    ('cansu tan', 'biology', 43),
    ('cenk yilmaz', 'biology', 34),
    ('gul yilmaz', 'biology', 37),
    ('salih kaya', 'biology', 42),
    ('aykut tan', 'biology', 60),
    ('melike yilmaz', 'biology', 28),
    ('meltem kaya', 'biology', 56),
    ('dicle tan', 'biology', 35),
    ('baris yilmaz', 'biology', 30),
    ('seren kaya', 'biology', 50);
